KAFKA_SERVER = "broker:29092"
KAFKA_SECURITY_PROTOCOL = "PLAINTEXT"

KAFKA_TOPIC_ORDER = "order_details"
KAFKA_TOPIC_PAYMENT = "order_payment"
KAFKA_TOPIC_SENT_NOTIFY = "order_sent_notify"
KAFKA_TOPIC_ANALYTIC = "order_analytic"

APP_DATETIME_STR_FORMAT = "%d-%m-%Y %H:%M:%S"
APP_ORDER_SERVICE_HOST = "0.0.0.0"
APP_ORDER_SERVICE_PORT = 5002
